//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dias.rc
//
#define ID_IMAGE_STAT_INFO              3
#define ID_IMAGE_MODEL_BW               11
#define IDD_ABOUTBOX                    100
#define ID_IMAGE_NAME                   103
#define IDD_TBP_MRKCREATE               103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_PATCH_NAME                   104
#define ID_SURVEY_NAME                  105
#define ID_PATCH_CONTRCOLOR             106
#define ID_PATCH_COLORMASK              107
#define ID_INDICATOR_TOOL               108
#define ID_INDICATOR_SAVE               109
#define ID_INDICATOR_PRINT              110
#define ID_INDICATOR_PROGRAM            111
#define ID_INDICATOR_IMG                112
#define ID_INDICATOR_SRV                113
#define ID_INDICATOR_REP                114
#define ID_INDICATOR_SIZEICO            115
#define ID_INDICATOR_SIZE               116
#define ID_INDICATOR_CMICO              117
#define ID_INDICATOR_CM                 118
#define ID_INDICATOR_BPP                119
#define ID_INDICATOR_TIME               120
#define ID_INDICATOR_GEOMSCALE          123
#define ID_INDICATOR_DENSSCALE          124
#define ID_INDICATOR_GEOMSCALEICO       125
#define ID_INDICATOR_DENSSCALEICO       126
#define IDR_MAINFRAME                   128
#define IDR_DISTYPE                     129
#define IDB_REBAR                       131
#define ID_INDICATOR_PROGRAMICO         132
#define ID_INDICATOR_PRINTICO           133
#define ID_INDICATOR_IMGICO             134
#define ID_INDICATOR_CNLICO             135
#define ID_INDICATOR_CNL                136
#define ID_INDICATOR_PTCICO             137
#define ID_INDICATOR_PTC                138
#define IDB_TBX_DOC_N                   139
#define ID_INDICATOR_MRK                139
#define IDR_POPUP_DOC_EMPTY             140
#define ID_INDICATOR_MRKICO             140
#define IDR_POPUP_DOC_ITEM              141
#define IDR_TBX_DOC                     143
#define IDR_TBX_DOC_IMG                 143
#define IDB_IL_DOCTYPES                 153
#define IDR_POPUP_DOC_ADDIMG            154
#define IDR_POPUP_DOC_ADDDB             155
#define IDR_POPUP_DOC_ADDRPT            156
#define IDR_TBX_IMAGES                  157
#define IDD_DOC_ADD_IMAGES              160
#define IDD_DOC_NEW                     161
#define IDR_POPUP_DOC_ZOOM              163
#define IDC_POINTER                     164
#define IDC_IOBJCREATE                  166
#define IDC_MRKCREATE                   167
#define IDCX_ZOOMIN_AREASEL             168
#define IDC_CURSOR2                     169
#define IDC_CURSOR3                     170
#define IDC_CURSOR4                     171
#define IDCX_IOBJPTR_MOVE               175
#define IDC_MRKPTR                      176
#define IDC_TEXTCNG                     177
#define IDC_CURSOR11                    178
#define IDC_TEXTCREATE                  179
#define IDB_TBX_STD_H                   180
#define IDB_TBX_STD_N                   181
#define IDB_TBX_STD_D                   182
#define IDR_TBP_MARKERS                 186
#define IDR_TBP_IMAGE                   188
#define IDR_TBX_SURVEIS                 189
#define IDB_TBP_IMAGE_H                 190
#define IDI_WS_MARKER_CENTER            191
#define IDR_TBX_DOC_SRV                 191
#define IDI_WS_MARKER_ZOOM              192
#define IDD_COUNT                       192
#define IDR_TBX_DOC_REP                 192
#define IDD_START                       193
#define IDR_POPUP_MARKER_STYLE          195
#define IDR_POPUP_MARKER_KERNEL         196
#define IDD_MENUCOUNT                   196
#define ID_MARKER_KRNLSTYLE             200
#define IDR_POPUP_MARKER_KRNLSTYLE      200
#define ID_MARKER_SHPSTYLE              201
#define IDI_COLOR_MODEL_BW              201
#define IDR_POPUP_MARKER_SHPSTYLE       201
#define IDI_COLOR_MODEL_GRAY            202
#define IDB_LOGO                        202
#define IDI_COLOR_MODEL_RGB             203
#define IDB_IL_COLORMODELS              203
#define IDI_COLOR_MODEL_CMY             204
#define IDI_COLOR_MODEL_LAB             205
#define IDI_COLOR_MODEL_CMYK            206
#define IDD_DOC_ADD_IMPORT              206
#define IDI_MRKCREATE                   207
#define IDI_PIC_SIZE                    208
#define ID_MARKER_KRNLSTYLE_NAME0       210
#define IDI_CONTEXTHELP                 210
#define IDS_MARKER_KRNLSTYLE_NONE       210
#define IDB_MARKER_KRNLSTYLE_NONE       210
#define ID_MARKER_KRNLSTYLE_NAME1       211
#define IDD_TOOLBOX                     211
#define IDI_PIC_OFFX                    211
#define IDS_MARKER_KRNLSTYLE_ROUND      211
#define IDB_MARKER_KRNLSTYLE_ROUND      211
#define ID_MARKER_KRNLSTYLE_NAME2       212
#define IDI_PIC_OFFY                    212
#define IDS_MARKER_KRNLSTYLE_X          212
#define IDB_MARKER_KRNLSTYLE_X          212
#define ID_MARKER_KRNLSTYLE_NAME3       213
#define IDI_PIC_FILL                    213
#define IDS_MARKER_KRNLSTYLE_CROSS      213
#define IDB_MARKER_KRNLSTYLE_CROSS      213
#define ID_MARKER_SHPSTYLE_NAME0        214
#define IDI_PIC_SIZEX                   214
#define IDS_MARKER_SHPSTYLE_NONE        214
#define ID_MARKER_SHPSTYLE_NAME1        215
#define IDI_PIC_SIZEY                   215
#define IDS_MARKER_SHPSTYLE_ELLIPSE     215
#define ID_MARKER_SHPSTYLE_NAME2        216
#define IDI_PIC_ROTATE                  216
#define IDS_MARKER_SHPSTYLE_TRIANGLE    216
#define ID_MARKER_SHPSTYLE_NAME3        217
#define IDI_PIC_LOCKED                  217
#define IDS_MARKER_SHPSTYLE_RECTANGLE   217
#define IDI_PIC_UNLOCKED                218
#define IDI_MRK_CENTER                  219
#define IDD_CAPTURE                     220
#define IDI_PIC_RIGTHARROW              221
#define IDI_PIC_DOWNARROW               222
#define IDD_PREF_DENSSCALE              223
#define IDB_DENSSCALES                  224
#define IDD_PREF_GEOMSCALE              224
#define IDB_DENSTYPES                   225
#define IDI_INDICATOR_GEOMSCALE         226
#define IDI_INDICATOR_DENSSCALE         227
#define IDB_GEOMSCALES                  227
#define IDD_COMBODLG                    228
#define IDB_MARKER_SHPSTYLE_NONE        228
#define IDI_GRIPPER                     229
#define IDB_MARKER_SHPSTYLE_ELLIPSE     229
#define IDI_BUTTON                      230
#define IDB_MARKER_SHPSTYLE_TRIANGLE    230
#define IDC_HAND                        231
#define IDB_MARKER_SHPSTYLE_RECTANGLE   231
#define IDI_PIC_UP                      231
#define IDD_DOC_ADD_SURVEY              232
#define IDI_PIC_DOWN                    232
#define IDI_PIC_REMOVE                  233
#define IDD_PREF_SAVE                   234
#define IDI_PIC_PREVIEW                 234
#define IDD_TBP_IMAGE                   235
#define IDD_FN_3IMG                     236
#define IDI_PIC_HAND                    237
#define IDI_PIC_ZOOM                    238
#define IDI_PIC_ZOOM1                   239
#define IDB_IL_OBJECTS                  239
#define IDI_PIC_ZOOMFIT                 240
#define IDB_IL_FIELDTYPES               240
#define IDI_PIC_TOGGLE                  241
#define IDI_INDICATOR_IMGICO            243
#define IDI_INDICATOR_CNLICO            244
#define IDI_INDICATOR_PTCICO            245
#define IDI_INDICATOR_MRKICO            246
#define IDI_INDICATOR_PRG_STOP          247
#define IDI_INDICATOR_PRG_PAUSE         248
#define IDI_INDICATOR_PRG_START         249
#define IDI_INDICATOR_SAVE              250
#define IDI_INDICATOR_OPEN              251
#define IDI_INDICATOR_IMPORT            252
#define IDI_INDICATOR_EXPORT            253
#define IDD_FILTER                      254
#define IDD_TBP_MRKSELECT               255
#define IDD_TITLES                      256
#define IDI_ICON_IMAGES                 257
#define IDI_ICON_SURVEY                 258
#define IDI_POINTER                     259
#define IDB_TBX_IMG_N                   260
#define IDB_TBX_IMG_H                   261
#define IDC_DN_DIMX                     1003
#define IDC_DN_DIMY                     1004
#define IDC_DAI_COUNT                   1005
#define IDC_DN_BPP                      1005
#define IDC_DN_MODEL                    1007
#define IDC_DN_COUNT                    1008
#define IDC_COUNT_PROMPT                1012
#define IDC_COUNT_COUNT                 1013
#define IDC_COUNT_SPIN                  1014
#define IDC_START_START                 1015
#define IDC_START_NEW                   1016
#define IDC_START_ACQUIRE               1017
#define IDC_START_RECENT                1018
#define IDC_START_LOAD                  1019
#define IDC_START_DEFAULT               1020
#define IDC_START_LIST                  1021
#define IDC_SLIDER1                     1022
#define IDC_MC_SLIDER                   1022
#define IDC_EDIT1                       1023
#define IDC_MC_VALUE                    1023
#define IDC_DN_DESCRIPTION              1023
#define IDC_DS_NAME                     1023
#define IDC_MC_UNITS                    1024
#define IDC_DS_DESCR                    1024
#define IDC_EDIT2                       1024
#define IDC_DS_A                        1025
#define IDC_EDIT3                       1025
#define IDC_DS_B                        1026
#define IDC_DS_UNITS                    1027
#define IDC_DN_BACKGROUND               1032
#define IDC_DN_DEPTH                    1033
#define IDC_DN_NAME                     1034
#define IDC_DN_BG_WHITE                 1036
#define IDC_DN_BG_BLACK                 1037
#define IDC_DN_BG_CUSTOM                1038
#define IDC_DN_CREATE_MANUAL            1039
#define IDC_DN_CREATE_ARCUIRE           1040
#define IDC_DN_SOURCE                   1041
#define IDC_DN_MODELS                   1048
#define IDC_DAI_SIZE_DOC                1049
#define IDC_DAI_SIZE_IMG                1050
#define IDC_DAI_MODEL_DOC               1051
#define IDC_DAI_MODEL_IMG               1052
#define IDC_DAI_DEPTH_DOC               1053
#define IDC_DAI_DEPTH_IMG               1054
#define IDC_MRKPB_SELECT                1059
#define IDC_MRKPB_HIDE                  1060
#define IDC_MRKPB_SHOW                  1061
#define IDC_MRKPB_STYLE                 1062
#define IDC_PB_CONTEXTHELP              1063
#define IDC_MRKPB_KERNEL                1064
#define IDC_MRKPB_KRNLSIZE              1065
#define IDC_MRKPB_KRNLCOLOR             1069
#define IDC_MRKPB_SHAPE                 1070
#define IDC_MRKPB_SHPX                  1071
#define IDC_MRKPB_SHPY                  1072
#define IDC_MRKPB_SHPROT                1073
#define IDC_MRKPB_SHPCOL                1074
#define IDC_MRKPB_FILLCOL               1075
#define IDC_PB_TOOL                     1076
#define IDC_BUTTON1                     1077
#define IDC_MRKPB_ICO_KRNLSIZE          1078
#define IDC_DS_REMOVE                   1078
#define IDC_BUTTON2                     1078
#define IDC_MRKPB_ICO_KRNLCOL           1082
#define IDC_MRKPB_ICO_SHPX              1085
#define IDC_MRKPB_ICO_SHPY              1086
#define IDC_MRKPB_ICO_SHPROT            1087
#define IDC_MRKPB_ICO_SHPCOL            1088
#define IDC_MRKPB_ICO_FILLCOL           1089
#define IDC_MRKPB_SHPX_LOCK             1090
#define IDC_MRKPB_SIZE_LOCK             1090
#define IDC_MRKPB_SHPY_LOCK             1091
#define IDC_MRKPB_SHPROT_LOCK           1092
#define IDC_CAPTURE_WND                 1093
#define IDC_CAPTURE_TOGGLE              1094
#define IDC_CAPTURE_CAPTURE             1095
#define IDC_CAPTURE_OPTIONS             1096
#define IDC_MC_RADIOPX                  1099
#define IDC_MC_RADIOSYS                 1100
#define IDC_DS_LIST                     1100
#define IDC_DS_TYPES                    1101
#define IDC_DS_SELECT                   1103
#define IDC_DS_ADD                      1104
#define IDC_GS_LIST                     1105
#define IDC_GS_ADD                      1106
#define IDC_GS_REMOVE                   1107
#define IDC_GS_SELECT                   1108
#define IDC_GS_NAME                     1109
#define IDC_GS_DESCR                    1110
#define IDC_GS_A                        1111
#define IDC_GS_B                        1112
#define IDC_GS_UNITS                    1113
#define IDC_CD_LIST                     1114
#define IDC_CD_BUTTON                   1115
#define IDC_CD_GRIPPER                  1116
#define IDC_DAS_TREE                    1117
#define IDC_DAS_INFO                    1118
#define IDC_DAS_LIST                    1120
#define IDC_RADIO1                      1122
#define IDC_RADIO2                      1123
#define IDC_RADIO3                      1124
#define IDC_CAPTURE_POSAFTER            1125
#define IDC_COMBO1                      1126
#define IDC_CAPTURE_POSBEFORE           1126
#define IDC_CHECK2                      1127
#define IDC_3IFN_3TYPE                  1127
#define IDC_CHECK3                      1128
#define IDC_3IFN_1TYPE                  1128
#define IDC_CHECK4                      1129
#define IDC_CHECK5                      1130
#define IDC_IMGPB_NAME                  1130
#define IDC_CHECK6                      1131
#define IDC_IMGPB_DESCR                 1131
#define IDC_COMBO2                      1132
#define IDC_IMGPB_HIDE                  1132
#define IDC_IMGPB_DESCRTEMPL            1132
#define IDC_COMBO3                      1133
#define IDC_IMGPB_SHOW                  1133
#define IDC_CAPTURE_SAVE                1133
#define IDC_COMBO4                      1134
#define IDC_CAPTURE_IMPORT              1134
#define IDC_IMGPB_NAMETEMPL             1134
#define IDC_COMBO5                      1135
#define IDC_CAPTURE_DELETE              1135
#define IDC_COMBO6                      1136
#define IDC_CHECK1                      1137
#define IDC_EDIT4                       1138
#define IDC_RADIO4                      1139
#define IDC_RADIO5                      1140
#define IDC_CHECK7                      1141
#define IDC_CHECK8                      1142
#define IDC_CHECK9                      1143
#define IDC_EDIT5                       1144
#define IDC_3IFN_RESET                  1146
#define IDC_DAS_UP                      1147
#define IDC_3IFN_APPLY                  1147
#define IDC_DAS_DOWN                    1148
#define IDC_DAS_REMOVE                  1149
#define IDC_3IFN_2TYPE                  1152
#define IDC_3IFN_1SRC                   1153
#define IDC_3IFN_2SRC                   1154
#define IDC_3IFN_PREVIEW                1155
#define IDC_3IFN_3SRC                   1156
#define IDC_CAPTURE_IMGNAME             1157
#define IDC_CAPTURE_POSTOP              1158
#define IDC_CAPTURE_POSEND              1159
#define IDC_CAPTURE_AUTONAME            1160
#define IDC_3IFN_AUTO                   1161
#define IDC_CAPTURE_NO                  1161
#define IDC_3IFN_HAND                   1162
#define IDC_DAS_OBJECT                  1162
#define IDC_CAPTURE_STEP                1162
#define IDC_3IFN_ZOOM                   1163
#define IDC_DAS_LOAD                    1163
#define IDC_CAPTURE_SEQNO               1163
#define IDC_3IFN_ZOOM1                  1164
#define IDC_DAS_SAVE                    1164
#define IDC_CAPTURE_SEQ                 1164
#define IDC_3IFN_ZOOMFIT                1165
#define IDC_DAS_DESCRIPT                1165
#define IDC_CAPTURE_SEQNAME             1165
#define IDC_3IFN_TOGGLE                 1166
#define IDC_CAPTURE_AUTO                1166
#define IDC_FLT_IMG1                    1166
#define IDC_CAPTURE_SEC                 1167
#define IDC_FLT_IMG2                    1167
#define IDC_CAPTURE_INTEGR              1168
#define IDC_FLT_PARAM                   1168
#define IDC_CAPTURE_INTERGNO            1169
#define IDC_FLT_IMG1WHO                 1169
#define IDC_FLT_HISTORY                 1170
#define IDC_FLT_IMG1WHO2                1171
#define IDC_FLT_FUNCTIONS               1172
#define IDC_FLT_APPLY                   1173
#define IDC_FLT_IMG1WHO3                1174
#define IDC_FLT_IMG1WHO4                1175
#define IDC_TITLES_TITLE                1175
#define IDC_TITLES_DESCR                1176
#define IDC_CD_NEW                      1177
#define IDC_CAPTURE_PRESENTS            1177
#define IDC_CD_TOP                      1178
#define IDC_DAI_SELECT                  1178
#define IDC_CD_UP                       1179
#define IDC_DAI_SELECTADD               1179
#define IDC_CD_DELETE                   1180
#define IDC_DAI_NAME                    1180
#define IDC_CD_DOWN                     1181
#define IDC_DAI_DESCR                   1181
#define IDC_CD_BOTTOM                   1182
#define IDC_CD_MENU                     1183
#define IDC_DAI_TEMPL2                  1183
#define IDC_DAI_TEMPL3                  1184
#define IDC_DAI_POSTOP                  1185
#define IDC_DAI_POSEND                  1186
#define IDC_DAI_POSBEFOREACT            1187
#define IDC_DAI_POSAFTERACT             1188
#define IDC_DAI_POSBEFORESEL            1189
#define IDC_DAS_NAME                    1189
#define IDC_DAI_POSAFTERSEL             1190
#define IDC_DAS_DESCR                   1190
#define IDC_DAI_POSEVERY                1191
#define IDC_DAS_IMPORT                  1191
#define IDC_DAS_DELETE                  1192
#define IDC_DAS_PRESENTS                1193
#define IDC_DN_PRESENTS                 1194
#define IDC_DN_SAVE                     1195
#define IDC_DN_IMPORT                   1196
#define IDC_DN_DELETE                   1197
#define IDC_DN_DEVICES                  1198
#define ID_TOOLS_GEOMSCALE_1            24000
#define ID_TOOLS_GEOMSCALE_999          24999
#define ID_TOOLS_DENSSCALE_1            25000
#define ID_TOOLS_DENSSCALE_999          25999
#define IDC_ZOOMIN                      30978
#define IDC_ZOOMOUT                     30988
#define IDCX_ZOOMOUT_AREASEL            30989
#define IDC_MRKPTR_MOVE                 30990
#define IDC_MRKPTR_SIZEX                30991
#define IDC_MRKPTR_SIZEY                30992
#define IDC_MRKPTR_SIZEXY               30993
#define IDC_MRKPTR_ROT                  30995
#define IDC_MRKSEL                      30996
#define IDC_MRKPTR_SIZEYROT             30998
#define IDC_MRKPTR_SIZEXYROT            30999
#define IDC_MRKPTR_SIZEXROT             31000
#define IDC_HANDSHAKE                   31001
#define ID_EDIT_ADD                     32771
#define ID_EDIT_REMOVE                  32782
#define ID_EDIT_UP                      32783
#define ID_EDIT_DOWN                    32784
#define ID_EDIT_PREV                    32785
#define ID_EDIT_NEXT                    32786
#define ID_EDIT_PROP                    32787
#define ID_DOC_STYLE                    32788
#define ID_EDIT_STYLE_BIG               32789
#define ID_EDIT_STYLE_SMALL             32790
#define ID_DOC_ADD_IMAGE                32791
#define ID_DOC_ADD_SEQUENCE             32792
#define ID_DOC_ADD_ACQUIRE              32793
#define ID_DOC_ADD                      32794
#define ID_DOC_REMOVE                   32795
#define ID_DOC_UP                       32796
#define ID_DOC_DOWN                     32797
#define ID_DOC_PREV                     32798
#define ID_DOC_NEXT                     32799
#define ID_DOC_PROP                     32800
#define ID_TOOLBOX_PTR                  32801
#define ID_TOOLBOX_ZOOMIN               32802
#define ID_TOOLBOX_MARKPTR              32803
#define ID_TOOLBOX_MARK                 32804
#define ID_TOOLBOX_TEXT                 32805
#define ID_TOOLBOX_OBJ                  32806
#define ID_TOOLBOX_OBJPTR               32807
#define ID_TOOLBOX_ZOOMOUT              32809
#define ID_TOOLBOX_HAND                 32810
#define ID_TOOLBOX_INFO                 32813
#define ID_TOOLBOX_METER                32814
#define ID_TOOLBOX_OBJCNG               32815
#define ID_TOOLBOX_TEXTPTR              32816
#define ID_DOC_ADD_IMPORTIMG            32817
#define ID_DOC_ADD_IMPORTSEQ            32818
#define ID_DOC_ADD_REPORT               32819
#define ID_DOC_ADD_DB                   32820
#define ID_DOC_ADD_DBMEASURE            32821
#define ID_DOC_ADD_IMPORTDB             32822
#define ID_VIEW_TOOLBAR_STD             32823
#define ID_VIEW_TOOLBOX                 32824
#define ID_VIEW_IMAGES                  32825
#define ID_VIEW_DATA                    32826
#define ID_VIEW_REPORTS                 32827
#define ID_VIEW_CLIENT                  32828
#define ID_TOOLBOX_SELECT               32829
#define ID_VIEW_ZOOM                    32830
#define ID_TOOLBOX_ZOOM                 32830
#define ID_VIEW_ZOOM_FIT                32832
#define ID_VIEW_ZOOM_1TO1               32833
#define ID_VIEW_ZOOM_25                 32834
#define ID_VIEW_ZOOM_33                 32835
#define ID_VIEW_ZOOM_50                 32836
#define ID_VIEW_ZOOM_66                 32837
#define ID_VIEW_ZOOM_75                 32838
#define ID_VIEW_ZOOM_125                32839
#define ID_VIEW_ZOOM_150                32840
#define ID_VIEW_ZOOM_200                32841
#define ID_VIEW_ZOOM_300                32842
#define ID_VIEW_ZOOM_400                32843
#define ID_VIEW_ZOOM_500                32844
#define ID_VIEW_ZOOM_750                32845
#define ID_VIEW_ZOOM_250                32846
#define ID_VIEW_ZOOM_1000               32847
#define ID_VIEW_ZOOM_OTHER              32848
#define ID_MARKER_KRNLY                 32850
#define ID_MARKER_KRNLSIZE              32850
#define ID_MARKER_KRNLX                 32851
#define ID_MARKER_SHPY                  32853
#define ID_MARKER_SHPX                  32854
#define ID_MARKER_STYLE                 32855
#define ID_MARKER_INTCOL                32856
#define ID_MARKER_SELSTYLE              32860
#define ID_MARKER_KRNLCOL               32861
#define ID_MARKER_SHPCOL                32862
#define ID_IMAGE_LUT                    32863
#define ID_IMAGE_GEOMSCALE              32864
#define ID_IMAGE_DENSSCALE              32865
#define ID_MARKER_SHPROT                32867
#define ID_MARKER_SIZELOCK              32868
#define ID_MARKER_ROTLOCK               32870
#define ID_MARKER_COPYSTYLE             32872
#define ID_MARKER_HELP                  32873
#define ID_MARKER_KERNEL_ROUND          32874
#define ID_MARKER_KERNEL_PLUS           32876
#define ID_MARKER_KERNEL_NONE           32877
#define ID_MARKER_STYLE_ADD             32879
#define ID_MARKER_KERNEL_X              32881
#define ID_PATCH_CREATEFROM             32884
#define ID_IMAGE_SEG_GENPATCH           32884
#define ID_PATCH_DELETE                 32885
#define ID_PATCH_DELETEALL              32886
#define ID_PATCH_MOVETO                 32887
#define ID_PATCH_COPYTO                 32888
#define ID_PATCH_SELECTALL              32889
#define ID_PATCH_DISPLAY                32890
#define ID_PATCH_MEASURE                32891
#define ID_PATCH_MEASUREALL             32892
#define ID_PATCH_EXPORT                 32893
#define ID_PATCH_IMPORT                 32894
#define ID_EDIT_RENAME                  32895
#define ID_EDIT_SELECT                  32896
#define ID_FILE_SAVEWEB                 32899
#define ID_FILE_INFO                    32900
#define ID_FILE_JUMP_LIGA               32901
#define ID_FILE_JUMP_STANUM             32902
#define ID_FILE_JUMP_SPIDER             32903
#define ID_IMAGE_RESAMPLE               32907
#define ID_IMAGE_CROP                   32909
#define ID_EDIT_DUPLICATE               32910
#define ID_EDIT_PREFERENCES             32913
#define ID_IMAGE_ARITHM_ADD             32915
#define ID_IMAGE_ARITHM_SUB             32916
#define ID_IMAGE_ARITHM_MUL             32917
#define ID_IMAGE_ARITHM_DIV             32918
#define ID_IMAGE_ARITM_CMB              32919
#define ID_IMAGE_ARITHM_MIN             32920
#define ID_IMAGE_STAT_MIN               32920
#define ID_IMAGE_MAX                    32921
#define ID_IMAGE_STAT_MAX               32921
#define ID_IMAGE_ARITHM_AVG             32922
#define ID_IMAGE_STAT_AVG               32922
#define ID_IMAGE_BOOL_OR                32923
#define ID_IMAGE_BOOL_AND               32924
#define ID_IMAGE_BOOL_XOR               32925
#define ID_IMAGE_BOOL_NOT               32926
#define ID_IMAGE_SEG_FROMPATCH          32927
#define ID_IMAGE_SEG_FROMMARKS          32928
#define ID_IMAGE_SEG_SEGMENT            32929
#define ID_IMAGE_SEG_MULTISEG           32930
#define ID_IMAGE_SEG_ERODE              32931
#define ID_IMAGE_SEG_DILATE             32932
#define ID_IMAGE_SEG_OPEN               32933
#define ID_IMAGE_SEG_CLOSE              32934
#define ID_IMAGE_SEG_FILTER             32935
#define ID_IMAGE_SEG_FILLHOLES          32936
#define ID_IMAGE_SEG_EXTRHOLES          32937
#define ID_IMAGE_SEG_EXTRCONT           32938
#define ID_IMAGE_ARITHM_MOD             32939
#define ID_IMAGE_SEG_SEGREGATE          32940
#define ID_IMAGE_SEG_SEGINFRAME         32941
#define ID_EDIT_BIG                     32942
#define ID_EDIT_SMALL                   32943
#define ID_VIEW_TOOLBAR_EDIT            32944
#define ID_FILE_SAVEAS                  32945
#define ID_FILE_ACQUIRE_SELECTCAMERA    32946
#define ID_IMAGE_ACQUIRE_CAMERA         32947
#define ID_FILE_IMPORT                  32949
#define ID_FILE_EXPORT                  32950
#define ID_IMAGE_MODEL_GREYSCALE        32951
#define ID_IMAGE_MODEL_RGB              32952
#define ID_IMAGE_MODEL_CMY              32953
#define ID_IMAGE_MODEL_CMYK             32954
#define ID_IMAGE_MODEL_LAB              32955
#define ID_IMAGE_BPP_1                  32956
#define ID_IMAGE_BPP_4                  32957
#define ID_IMAGE_BPP_8                  32958
#define ID_IMAGE_BPP_16                 32959
#define ID_IMAGE_BPP_32                 32960
#define ID_IMAGE_BPP_OTHER              32961
#define ID_IMAGE_MODEL_MULTY            32962
#define ID_IMAGE_ROTATE_90CW            32963
#define ID_IMAGE_ROTATE_90CCW           32964
#define ID_IMAGE_ROTATE_180             32965
#define ID_IMAGE_ROTATE_ARBITRARY       32966
#define ID_IMAGE_ROTATE_FLIPVERT        32967
#define ID_IMAGE_ROTATE_FLIPHORZ        32968
#define ID_IMAGE_ADJUST_NORMALIZE       32969
#define ID_IMAGE_ADJUST_LINEARIZE       32970
#define ID_WINDOW_CLOSE                 32971
#define ID_WINDOW_MINIMIZE              32972
#define ID_WINDOW_MAXIMIZE              32973
#define ID_EDIT_CUSTOMIZE               32974
#define ID_VIEW_ZOOMIN                  32975
#define ID_VIEW_ZOOMOUT                 32976
#define ID_VIEW_FULLSCREEN              32977
#define ID_VIEW_HIDE                    32978
#define ID_VIEW_SHOWALL                 32979
#define ID_VIEW_PROPBAR                 32980
#define ID_HELP_PLUGIN_LIST             32983
#define ID_HELP_FEEDBACK                32984
#define ID_HELP_HELPER                  32985
#define ID_TOOLBOX_MARKSEL              32986
#define ID_TOOLBOX_METERPTR             32987
#define ID_FILE_MAIL                    32988
#define ID_EDIT_DELETE                  32989
#define ID_IMAGE_PLUGINS                32990
#define ID_SURVEY_MEASURE               32999
#define ID_EDIT_GEOMSCALES              33000
#define ID_EDIT_DENSSCALES              33001
#define ID_VIEW_SCALE                   33002
#define ID_VIEW_IMAGE                   33003
#define ID_VIEW_PATCHES                 33004
#define ID_VIEW_MARKS                   33005
#define ID_VIEW_TEXTS                   33006
#define ID_VIEW_METRICS                 33007
#define ID_VIEW_HEADERS                 33008
#define ID_TOOLS_PREFERENCES            33009
#define ID_TOOLS_IMPORTPREFS            33010
#define ID_TOOLS_EXPORTPREFS            33011
#define ID_TOOLS_MACRO                  33012
#define ID_IMAGE_IMPORT                 33014
#define ID_IMAGE_EXPORT                 33015
#define ID_SURVEY_IMPORT                33016
#define ID_SURVEY_EXPORT                33017
#define ID_TOOLS_PLUGINS_1              33022
#define ID_IMAGE_ADJUST_LINSCALE        33023
#define ID_IMAGE_ADJUST_SCALE           33024
#define ID_IMAGE_STAT_HIST              33025
#define ID_IMAGE_SMOOTH_LOWPAS          33026
#define ID_IMAGE_SMOOTH_SIGMA           33027
#define ID_IMAGE_SMOOTH_GAUSSIAN        33028
#define ID_IMAGE_EDGES_LAPLACIAN        33029
#define ID_IMAGE_ADD                    33031
#define ID_SURVEY_ADD                   33032
#define ID_IMAGE_ADDSEQ                 33033
#define ID_SURVEY_FIELDS                33034
#define ID_TOOLS_PLUGINS_2              33035
#define ID_IMG_DIAS_PXW_AND             33037
#define ID_IMG_DIAS_PXW_OR              33038
#define ID_IMG_DIAS_PXW_XOR             33039
#define ID_IMG_DIAS_PXW_NOt             33040
#define ID_IMG_DIAS_PXW_ADD             33041
#define ID_IMG_DIAS_PXW_SUB             33042
#define ID_IMG_DIAS_PXW_MUL             33043
#define ID_IMG_DIAS_PXW_DIV             33044
#define ID_IMG_DIAS_PXW_POW             33045
#define ID_IMG_DIAS_PXW_ROOT            33046
#define ID_IMG_DIAS_PXW_MIN             33047
#define ID_IMG_DIAS_PXW_MAX             33048
#define ID_IMG_DIAS_PXW_AVG             33049
#define ID_IMG_DIAS_PXW_MED             33050
#define ID_IMG_DIAS_PXW_STD             33051
#define ID_IMG_DIAS_PXW_SDS             33052
#define ID_IMG_DIAS_PXW_MDS             33053
#define ID_IMG_DIAS_PXW_EDS             33054
#define ID_IMG_DIAS_PXW_THR             33055
#define ID_IMG_DIAS_MTX_LOGIC           33056
#define ID_IMG_DIAS_MTX_SUM             33057
#define ID_IMG_DIAS_MTX_PRD             33058
#define ID_IMG_DIAS_MTX_MIN             33059
#define ID_IMG_DIAS_MTX_MAX             33060
#define ID_IMG_DIAS_MTX_AVG             33061
#define ID_IMG_DIAS_MTX_MED             33062
#define ID_IMG_DIAS_MTX_STD             33063
#define ID_IMG_DIAS_MTX_AND             33064
#define ID_IMG_DIAS_MTX_OR              33065
#define ID_IMG_DIAS_MTX_XOR             33066
#define ID_IMG_DIAS_MTX_GRAD            33067
#define ID_IMG_DIAS_MTX_DIV             33068
#define ID_IMG_DIAS_MTX_ROT             33069
#define ID_IMG_DIAS_MTX_LAPL            33070
#define ID_IMG_DIAS_MTX_FILTR           33071
#define ID_IMG_DIAS_TRC_HOLES           33072
#define ID_IMG_DIAS_TRC_SCRAP           33073
#define ID_IMG_DIAS_TRC_MARK            33074
#define ID_IMG_DIAS_TRC_MASK            33075
#define ID_IMG_DIAS_TRC_LINK            33076
#define ID_IMG_DIAS_TRC_WINDOW          33077
#define ID_IMG_DIAS_TRC_IDENT           33078
#define ID_IMG_DIAS_IMG_RESAMPL         33079
#define ID_IMG_DIAS_IMG_SCALE           33080
#define ID_IMG_DIAS_IMG_NORM            33081
#define ID_IMG_DIAS_IMG_LIN             33082
#define ID_IMG_DIAS_IMG_PRODUCT         33083
#define ID_TOOLS_PLUGINS_3              33084
#define ID_MARKER_SHAPE_NONE            33086
#define ID_MARKER_SHAPE_ELLIPSE         33087
#define ID_MARKER_SHAPE_TRI             33088
#define ID_MARKER_SHAPE_RECT            33089
#define ID_MARKER_STYLE_IMPORT          33090
#define ID_MARKER_STYLE_EXPORT          33091
#define ID_MARKER_STYLE_DELETE          33092
#define ID_MARKER_STYLE_RENAME          33094
#define ID_MARKER_STYLE_DUPLICATE       33095
#define ID_MARKER_AUTOIMPORT            33096
#define IDS_TBX_DOC_ADD                 61446
#define IDS_TBX_DOC_ADD_IMAGE           61446
#define IDS_TBX_DOC_REMOVE              61447
#define IDS_TBX_DOC_UP                  61448
#define IDS_TBX_DOC_DOWN                61449
#define IDS_TBX_DOC_ADD_ACQUIRE         61449
#define IDS_TBX_DOC_PREV                61450
#define IDS_TBX_DOC_NEXT                61451
#define IDS_TBX_DOC_PROP                61452
#define IDS_TBX_DOC_STYLE               61453
#define IDS_TBX_DOC_IMAGES              61454
#define IDS_TBX_DOC_DB                  61455
#define IDS_TBX_DOC_REPORTS             61456
#define IDS_TBX_IMG                     61457
#define IDS_IMAGE_DEFAULTNAME           61458
#define IDS_DATA_DEFAULTNAME            61459
#define IDS_REPORT_DEFAULTNAME          61460
#define IDS_IMPORTSEQ_DLGCAPTION        61461
#define IDS_IMPORTSEQ_DEFNAME           61462
#define IDS_IMPORTSEQ_OPENERR           61463
#define IDS_IMPORTSEQ_TYPEERR           61464
#define IDS_IMPORTSEQ_SIZEERR           61465
#define IDS_TBX_DOC_ZOOM                61466
#define IDS_ERR_SYS_MEMRES              61467
#define IDS_ERR_SYS_MEMCOM              61468
#define IDS_ERR_SYS_MEMDECOM            61469
#define IDS_ERR_SYS_MEMREL              61470
#define IDS_MARKER_COPYSTYLE            61471
#define IDS_MARKER_SELSTYLE             61472
#define IDS_TBP_MRKCREATE               61473
#define IDS_CM_BW                       61474
#define IDS_CM_GRAY                     61475
#define IDS_CM_RGB                      61476
#define IDS_CM_CMY                      61477
#define IDS_CM_CMYK                     61478
#define IDS_CM_LAB                      61479
#define IDS_ERR_DOC_VERSION             61480
#define IDS_ERR_DOC                     61481
#define IDS_COLORMODEL                  61482
#define IDS_BPP                         61483
#define IDS_CHANNELS                    61484
#define IDS_CM_MULTY                    61485
#define IDS_TBX_DOC_ADD_DB              61486
#define IDS_TBX_DOC_ADD_MEASURE         61487
#define IDS_TBX_DOC_MEASURE             61487
#define IDS_DLG_CAPTURE_LIVE            61488
#define IDS_DLG_CAPTURE_STOP            61489
#define IDS_REG_ROOT                    61490
#define IDS_MBTITLE_APP                 61491
#define IDS_MBTEXT_REGERR               61492
#define IDS_MBTEXT_FSETERR              61493
#define IDS_MBTEXT_FSETWERR             61494
#define IDS_PREFERENCES                 61495
#define IDS_DENS_COL_NAME               61496
#define IDS_DENS_COL_COEF1              61497
#define IDS_DENS_COL_COEF2              61498
#define IDS_DENS_COL_UNITS              61499
#define IDS_DENS_COL_DESCRIPT           61500
#define IDS_DENS_TYPE_LINEAR            61501
#define IDS_DENS_TYPE_POLY              61502
#define IDS_DENS_TYPE_EXP               61503
#define IDS_DENS_TYPE_LOG               61504
#define IDS_MBTEXT_REGWERR              61505
#define IDS_MRKKRNL_NAME                61506
#define IDS_TBX_DOC_IMPORT              61507
#define IDS_TBX_DOC_EXPORT              61508
#define IDS_IMGPB_SHOW                  61509
#define IDS_IMGPB_HIDE                  61510
#define IDS_MRKSHP_NAME                 61511
#define IDS_METRICS_PX                  61512
#define IDS_METRICS_PIXELS              61513
#define IDS_METRICS_DEGR                61514
#define IDS_METRICS_DEGREES             61515
#define IDS_MRKSTYLE_NAME               61516
#define IDS_MRKSTYLE_DESCR              61517
#define IDS_DLG_DAS_FIELDCAPTION        61518
#define IDS_DLG_DAS_FIELDNAME           61519
#define IDS_EXPORTSEQ_DLGCAPTION        61520
#define IDS_EXPORTSEQ_OPENERR           61521
#define IDS_MBTITLE_WARNING             61522
#define IDS_MBTEXT_ADDSRVDLG            61523
#define IDS_DLG_DAS_UNIT                61524
#define IDS_TBX_DOC_FIELDS              61525
#define IDS_DLG_DAS_APP                 61526
#define IDS_DLG_DAS_DOC                 61527
#define IDS_DLG_DAS_IMG                 61528
#define IDS_DLG_DAS_CHNL                61529
#define IDS_DLG_DAS_PTCH                61530
#define IDS_DLG_DAS_MRK                 61531
#define IDS_DLG_DAS_USR                 61532
#define IDS_STATUS_READY                61533
#define IDS_MBTEXT_DIASKS_NO            61534
#define IDS_MBTITLE_COLLISION           61535
#define IDS_MBTEXT_COLLISION            61536
#define IDS_MBTITLE_DELETE              61537
#define IDS_MBTEXT_DELETE               61538
#define IDS_MBTITLE_ERROR               61539
#define IDS_MBTEXT_BUILTINDELETION      61540

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        261
#define _APS_NEXT_COMMAND_VALUE         33097
#define _APS_NEXT_CONTROL_VALUE         1199
#define _APS_NEXT_SYMED_VALUE           141
#endif
#endif
